<Project Sdk="Microsoft.NET.Sdk">
  <ItemGroup>
    <PackageReference Include="Avalonia.Headless.XUnit" />
    <PackageReference Include="Avalonia.Skia" />
    <PackageReference Include="Avalonia.HarfBuzz" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\..\src\AvaWin.Controls\AvaWin.Controls.csproj" />
  </ItemGroup>
  <ItemGroup>
    <Content Include="..\..\src\AvaWin.Controls\Themes\*.xaml" Link="ThemeXaml\%(Filename)%(Extension)" CopyToOutputDirectory="PreserveNewest" />
  </ItemGroup>
</Project>
