// <auto-generated>
//   Generated by tools/gen-appbar-icons.py from appBarIcons.json.
//   Do not edit by hand. Run the script again instead.
// </auto-generated>

namespace AvaWin;

/// <summary>
/// The 196 named glyphs of Symbols.ttf that an AppBarCommand, NavBarCommand or SymbolIcon accepts.
/// Resolve a member to its glyph with <see cref="AppBarIcons.Glyph(AppBarIcon)"/>.
/// </summary>
public enum AppBarIcon
{
    /// <summary>The <c>accept</c> glyph (U+E10B).</summary>
    Accept,
    /// <summary>The <c>accounts</c> glyph (U+E168).</summary>
    Accounts,
    /// <summary>The <c>add</c> glyph (U+E109).</summary>
    Add,
    /// <summary>The <c>addfriend</c> glyph (U+E1E2).</summary>
    AddFriend,
    /// <summary>The <c>admin</c> glyph (U+E1A7).</summary>
    Admin,
    /// <summary>The <c>aligncenter</c> glyph (U+E1A1).</summary>
    AlignCenter,
    /// <summary>The <c>alignleft</c> glyph (U+E1A2).</summary>
    AlignLeft,
    /// <summary>The <c>alignright</c> glyph (U+E1A0).</summary>
    AlignRight,
    /// <summary>The <c>allapps</c> glyph (U+E179).</summary>
    AllApps,
    /// <summary>The <c>attach</c> glyph (U+E16C).</summary>
    Attach,
    /// <summary>The <c>attachcamera</c> glyph (U+E12D).</summary>
    AttachCamera,
    /// <summary>The <c>audio</c> glyph (U+E189).</summary>
    Audio,
    /// <summary>The <c>back</c> glyph (U+E112).</summary>
    Back,
    /// <summary>The <c>backtowindow</c> glyph (U+E1D8).</summary>
    BackToWindow,
    /// <summary>The <c>blockcontact</c> glyph (U+E1E0).</summary>
    BlockContact,
    /// <summary>The <c>bold</c> glyph (U+E19B).</summary>
    Bold,
    /// <summary>The <c>bookmarks</c> glyph (U+E12F).</summary>
    Bookmarks,
    /// <summary>The <c>browsephotos</c> glyph (U+E155).</summary>
    BrowsePhotos,
    /// <summary>The <c>bullets</c> glyph (U+E133).</summary>
    Bullets,
    /// <summary>The <c>calculator</c> glyph (U+E1D0).</summary>
    Calculator,
    /// <summary>The <c>calendar</c> glyph (U+E163).</summary>
    Calendar,
    /// <summary>The <c>calendarday</c> glyph (U+E161).</summary>
    CalendarDay,
    /// <summary>The <c>calendarreply</c> glyph (U+E1DB).</summary>
    CalendarReply,
    /// <summary>The <c>calendarweek</c> glyph (U+E162).</summary>
    CalendarWeek,
    /// <summary>The <c>camera</c> glyph (U+E114).</summary>
    Camera,
    /// <summary>The <c>cancel</c> glyph (U+E10A).</summary>
    Cancel,
    /// <summary>The <c>caption</c> glyph (U+E15A).</summary>
    Caption,
    /// <summary>The <c>cc</c> glyph (U+E190).</summary>
    Cc,
    /// <summary>The <c>cellphone</c> glyph (U+E1C9).</summary>
    CellPhone,
    /// <summary>The <c>characters</c> glyph (U+E164).</summary>
    Characters,
    /// <summary>The <c>clear</c> glyph (U+E106).</summary>
    Clear,
    /// <summary>The <c>clearselection</c> glyph (U+E1C5).</summary>
    ClearSelection,
    /// <summary>The <c>clock</c> glyph (U+E121).</summary>
    Clock,
    /// <summary>The <c>closepane</c> glyph (U+E126).</summary>
    ClosePane,
    /// <summary>The <c>comment</c> glyph (U+E134).</summary>
    Comment,
    /// <summary>The <c>contact</c> glyph (U+E13D).</summary>
    Contact,
    /// <summary>The <c>contact2</c> glyph (U+E187).</summary>
    Contact2,
    /// <summary>The <c>contactinfo</c> glyph (U+E136).</summary>
    ContactInfo,
    /// <summary>The <c>contactpresence</c> glyph (U+E181).</summary>
    ContactPresence,
    /// <summary>The <c>copy</c> glyph (U+E16F).</summary>
    Copy,
    /// <summary>The <c>crop</c> glyph (U+E123).</summary>
    Crop,
    /// <summary>The <c>cut</c> glyph (U+E16B).</summary>
    Cut,
    /// <summary>The <c>delete</c> glyph (U+E107).</summary>
    Delete,
    /// <summary>The <c>directions</c> glyph (U+E1D1).</summary>
    Directions,
    /// <summary>The <c>disableupdates</c> glyph (U+E194).</summary>
    DisableUpdates,
    /// <summary>The <c>disconnectdrive</c> glyph (U+E17A).</summary>
    DisconnectDrive,
    /// <summary>The <c>dislike</c> glyph (U+E19E).</summary>
    Dislike,
    /// <summary>The <c>dockbottom</c> glyph (U+E147).</summary>
    DockBottom,
    /// <summary>The <c>dockleft</c> glyph (U+E145).</summary>
    DockLeft,
    /// <summary>The <c>dockright</c> glyph (U+E146).</summary>
    DockRight,
    /// <summary>The <c>document</c> glyph (U+E130).</summary>
    Document,
    /// <summary>The <c>download</c> glyph (U+E118).</summary>
    Download,
    /// <summary>The <c>edit</c> glyph (U+E104).</summary>
    Edit,
    /// <summary>The <c>emoji</c> glyph (U+E11D).</summary>
    Emoji,
    /// <summary>The <c>emoji2</c> glyph (U+E170).</summary>
    Emoji2,
    /// <summary>The <c>favorite</c> glyph (U+E113).</summary>
    Favorite,
    /// <summary>The <c>filter</c> glyph (U+E16E).</summary>
    Filter,
    /// <summary>The <c>find</c> glyph (U+E11A).</summary>
    Find,
    /// <summary>The <c>flag</c> glyph (U+E129).</summary>
    Flag,
    /// <summary>The <c>folder</c> glyph (U+E188).</summary>
    Folder,
    /// <summary>The <c>font</c> glyph (U+E185).</summary>
    Font,
    /// <summary>The <c>fontcolor</c> glyph (U+E186).</summary>
    FontColor,
    /// <summary>The <c>fontdecrease</c> glyph (U+E1C6).</summary>
    FontDecrease,
    /// <summary>The <c>fontincrease</c> glyph (U+E1C7).</summary>
    FontIncrease,
    /// <summary>The <c>fontsize</c> glyph (U+E1C8).</summary>
    FontSize,
    /// <summary>The <c>forward</c> glyph (U+E111).</summary>
    Forward,
    /// <summary>The <c>fourbars</c> glyph (U+E1E9).</summary>
    FourBars,
    /// <summary>The <c>fullscreen</c> glyph (U+E1D9).</summary>
    FullScreen,
    /// <summary>The <c>globe</c> glyph (U+E12B).</summary>
    Globe,
    /// <summary>The <c>go</c> glyph (U+E143).</summary>
    Go,
    /// <summary>The <c>gotostart</c> glyph (U+E1E4).</summary>
    GoToStart,
    /// <summary>The <c>gototoday</c> glyph (U+E184).</summary>
    GoToToday,
    /// <summary>The <c>hangup</c> glyph (U+E137).</summary>
    HangUp,
    /// <summary>The <c>help</c> glyph (U+E11B).</summary>
    Help,
    /// <summary>The <c>hidebcc</c> glyph (U+E16A).</summary>
    HideBcc,
    /// <summary>The <c>highlight</c> glyph (U+E193).</summary>
    Highlight,
    /// <summary>The <c>home</c> glyph (U+E10F).</summary>
    Home,
    /// <summary>The <c>import</c> glyph (U+E150).</summary>
    Import,
    /// <summary>The <c>importall</c> glyph (U+E151).</summary>
    ImportAll,
    /// <summary>The <c>important</c> glyph (U+E171).</summary>
    Important,
    /// <summary>The <c>italic</c> glyph (U+E199).</summary>
    Italic,
    /// <summary>The <c>keyboard</c> glyph (U+E144).</summary>
    Keyboard,
    /// <summary>The <c>leavechat</c> glyph (U+E11F).</summary>
    LeaveChat,
    /// <summary>The <c>left</c> glyph (U+E112).</summary>
    Left,
    /// <summary>The <c>library</c> glyph (U+E1D3).</summary>
    Library,
    /// <summary>The <c>like</c> glyph (U+E19F).</summary>
    Like,
    /// <summary>The <c>likedislike</c> glyph (U+E19D).</summary>
    LikeDislike,
    /// <summary>The <c>link</c> glyph (U+E167).</summary>
    Link,
    /// <summary>The <c>list</c> glyph (U+E14C).</summary>
    List,
    /// <summary>The <c>mail</c> glyph (U+E119).</summary>
    Mail,
    /// <summary>The <c>mail2</c> glyph (U+E135).</summary>
    Mail2,
    /// <summary>The <c>mailforward</c> glyph (U+E120).</summary>
    MailForward,
    /// <summary>The <c>mailreply</c> glyph (U+E172).</summary>
    MailReply,
    /// <summary>The <c>mailreplyall</c> glyph (U+E165).</summary>
    MailReplyAll,
    /// <summary>The <c>manage</c> glyph (U+E178).</summary>
    Manage,
    /// <summary>The <c>map</c> glyph (U+E1C4).</summary>
    Map,
    /// <summary>The <c>mapdrive</c> glyph (U+E17B).</summary>
    MapDrive,
    /// <summary>The <c>mappin</c> glyph (U+E139).</summary>
    MapPin,
    /// <summary>The <c>memo</c> glyph (U+E1D5).</summary>
    Memo,
    /// <summary>The <c>message</c> glyph (U+E15F).</summary>
    Message,
    /// <summary>The <c>microphone</c> glyph (U+E1D6).</summary>
    Microphone,
    /// <summary>The <c>more</c> glyph (U+E10C).</summary>
    More,
    /// <summary>The <c>movetofolder</c> glyph (U+E19C).</summary>
    MoveToFolder,
    /// <summary>The <c>musicinfo</c> glyph (U+E142).</summary>
    MusicInfo,
    /// <summary>The <c>mute</c> glyph (U+E198).</summary>
    Mute,
    /// <summary>The <c>newfolder</c> glyph (U+E1DA).</summary>
    NewFolder,
    /// <summary>The <c>newwindow</c> glyph (U+E17C).</summary>
    NewWindow,
    /// <summary>The <c>next</c> glyph (U+E101).</summary>
    Next,
    /// <summary>The <c>onebar</c> glyph (U+E1E6).</summary>
    OneBar,
    /// <summary>The <c>openfile</c> glyph (U+E1A5).</summary>
    OpenFile,
    /// <summary>The <c>openlocal</c> glyph (U+E197).</summary>
    OpenLocal,
    /// <summary>The <c>openpane</c> glyph (U+E127).</summary>
    OpenPane,
    /// <summary>The <c>openwith</c> glyph (U+E17D).</summary>
    OpenWith,
    /// <summary>The <c>orientation</c> glyph (U+E14F).</summary>
    Orientation,
    /// <summary>The <c>otheruser</c> glyph (U+E1A6).</summary>
    OtherUser,
    /// <summary>The <c>outlinestar</c> glyph (U+E1CE).</summary>
    OutlineStar,
    /// <summary>The <c>page</c> glyph (U+E132).</summary>
    Page,
    /// <summary>The <c>page2</c> glyph (U+E160).</summary>
    Page2,
    /// <summary>The <c>paste</c> glyph (U+E16D).</summary>
    Paste,
    /// <summary>The <c>pause</c> glyph (U+E103).</summary>
    Pause,
    /// <summary>The <c>people</c> glyph (U+E125).</summary>
    People,
    /// <summary>The <c>permissions</c> glyph (U+E192).</summary>
    Permissions,
    /// <summary>The <c>phone</c> glyph (U+E13A).</summary>
    Phone,
    /// <summary>The <c>phonebook</c> glyph (U+E1D4).</summary>
    PhoneBook,
    /// <summary>The <c>pictures</c> glyph (U+E158).</summary>
    Pictures,
    /// <summary>The <c>pin</c> glyph (U+E141).</summary>
    Pin,
    /// <summary>The <c>placeholder</c> glyph (U+E18A).</summary>
    Placeholder,
    /// <summary>The <c>play</c> glyph (U+E102).</summary>
    Play,
    /// <summary>The <c>postupdate</c> glyph (U+E1D7).</summary>
    PostUpdate,
    /// <summary>The <c>preview</c> glyph (U+E295).</summary>
    Preview,
    /// <summary>The <c>previewlink</c> glyph (U+E12A).</summary>
    PreviewLink,
    /// <summary>The <c>previous</c> glyph (U+E100).</summary>
    Previous,
    /// <summary>The <c>priority</c> glyph (U+E182).</summary>
    Priority,
    /// <summary>The <c>protecteddocument</c> glyph (U+E131).</summary>
    ProtectedDocument,
    /// <summary>The <c>read</c> glyph (U+E166).</summary>
    Read,
    /// <summary>The <c>redo</c> glyph (U+E10D).</summary>
    Redo,
    /// <summary>The <c>refresh</c> glyph (U+E149).</summary>
    Refresh,
    /// <summary>The <c>remote</c> glyph (U+E148).</summary>
    Remote,
    /// <summary>The <c>remove</c> glyph (U+E108).</summary>
    Remove,
    /// <summary>The <c>rename</c> glyph (U+E13E).</summary>
    Rename,
    /// <summary>The <c>repair</c> glyph (U+E15E).</summary>
    Repair,
    /// <summary>The <c>repeatall</c> glyph (U+E1CD).</summary>
    RepeatAll,
    /// <summary>The <c>repeatone</c> glyph (U+E1CC).</summary>
    RepeatOne,
    /// <summary>The <c>reporthacked</c> glyph (U+E1DE).</summary>
    ReportHacked,
    /// <summary>The <c>reshare</c> glyph (U+E1CA).</summary>
    Reshare,
    /// <summary>The <c>right</c> glyph (U+E111).</summary>
    Right,
    /// <summary>The <c>rotate</c> glyph (U+E14A).</summary>
    Rotate,
    /// <summary>The <c>rotatecamera</c> glyph (U+E124).</summary>
    RotateCamera,
    /// <summary>The <c>save</c> glyph (U+E105).</summary>
    Save,
    /// <summary>The <c>savelocal</c> glyph (U+E159).</summary>
    SaveLocal,
    /// <summary>The <c>scan</c> glyph (U+E294).</summary>
    Scan,
    /// <summary>The <c>selectall</c> glyph (U+E14E).</summary>
    SelectAll,
    /// <summary>The <c>send</c> glyph (U+E122).</summary>
    Send,
    /// <summary>The <c>setlockscreen</c> glyph (U+E18C).</summary>
    SetLockScreen,
    /// <summary>The <c>settile</c> glyph (U+E18D).</summary>
    SetTile,
    /// <summary>The <c>settings</c> glyph (U+E115).</summary>
    Settings,
    /// <summary>The <c>shop</c> glyph (U+E14D).</summary>
    Shop,
    /// <summary>The <c>showbcc</c> glyph (U+E169).</summary>
    ShowBcc,
    /// <summary>The <c>showresults</c> glyph (U+E15C).</summary>
    ShowResults,
    /// <summary>The <c>shuffle</c> glyph (U+E14B).</summary>
    Shuffle,
    /// <summary>The <c>slideshow</c> glyph (U+E173).</summary>
    SlideShow,
    /// <summary>The <c>solidstar</c> glyph (U+E1CF).</summary>
    SolidStar,
    /// <summary>The <c>sort</c> glyph (U+E174).</summary>
    Sort,
    /// <summary>The <c>stop</c> glyph (U+E15B).</summary>
    Stop,
    /// <summary>The <c>stopslideshow</c> glyph (U+E191).</summary>
    StopSlideShow,
    /// <summary>The <c>street</c> glyph (U+E1C3).</summary>
    Street,
    /// <summary>The <c>switch</c> glyph (U+E13C).</summary>
    Switch,
    /// <summary>The <c>switchapps</c> glyph (U+E1E1).</summary>
    SwitchApps,
    /// <summary>The <c>sync</c> glyph (U+E117).</summary>
    Sync,
    /// <summary>The <c>syncfolder</c> glyph (U+E1DF).</summary>
    SyncFolder,
    /// <summary>The <c>tag</c> glyph (U+E1CB).</summary>
    Tag,
    /// <summary>The <c>target</c> glyph (U+E1D2).</summary>
    Target,
    /// <summary>The <c>threebars</c> glyph (U+E1E8).</summary>
    ThreeBars,
    /// <summary>The <c>touchpointer</c> glyph (U+E1E3).</summary>
    TouchPointer,
    /// <summary>The <c>trim</c> glyph (U+E12C).</summary>
    Trim,
    /// <summary>The <c>twobars</c> glyph (U+E1E7).</summary>
    TwoBars,
    /// <summary>The <c>twopage</c> glyph (U+E11E).</summary>
    TwoPage,
    /// <summary>The <c>underline</c> glyph (U+E19A).</summary>
    Underline,
    /// <summary>The <c>undo</c> glyph (U+E10E).</summary>
    Undo,
    /// <summary>The <c>unfavorite</c> glyph (U+E195).</summary>
    Unfavorite,
    /// <summary>The <c>unpin</c> glyph (U+E196).</summary>
    Unpin,
    /// <summary>The <c>unsyncfolder</c> glyph (U+E1DD).</summary>
    UnsyncFolder,
    /// <summary>The <c>up</c> glyph (U+E110).</summary>
    Up,
    /// <summary>The <c>upload</c> glyph (U+E11C).</summary>
    Upload,
    /// <summary>The <c>uploadskydrive</c> glyph (U+E183).</summary>
    UploadSkyDrive,
    /// <summary>The <c>video</c> glyph (U+E116).</summary>
    Video,
    /// <summary>The <c>videochat</c> glyph (U+E13B).</summary>
    VideoChat,
    /// <summary>The <c>view</c> glyph (U+E18B).</summary>
    View,
    /// <summary>The <c>viewall</c> glyph (U+E138).</summary>
    ViewAll,
    /// <summary>The <c>volume</c> glyph (U+E15D).</summary>
    Volume,
    /// <summary>The <c>webcam</c> glyph (U+E156).</summary>
    Webcam,
    /// <summary>The <c>world</c> glyph (U+E128).</summary>
    World,
    /// <summary>The <c>zerobars</c> glyph (U+E1E5).</summary>
    ZeroBars,
    /// <summary>The <c>zoom</c> glyph (U+E1A3).</summary>
    Zoom,
    /// <summary>The <c>zoomin</c> glyph (U+E12E).</summary>
    ZoomIn,
    /// <summary>The <c>zoomout</c> glyph (U+E1A4).</summary>
    ZoomOut,
}
