// <auto-generated>
//   Generated by tools/gen-appbar-icons.py from appBarIcons.json.
//   Do not edit by hand. Run the script again instead.
// </auto-generated>

#nullable enable

using System;
using System.Collections.Generic;

namespace AvaWin;

/// <summary>Glyph lookup for <see cref="AppBarIcon"/>.</summary>
public static class AppBarIcons
{
    private static readonly string[] s_glyphs =
    [
        "\uE10B", // Accept (accept)
        "\uE168", // Accounts (accounts)
        "\uE109", // Add (add)
        "\uE1E2", // AddFriend (addfriend)
        "\uE1A7", // Admin (admin)
        "\uE1A1", // AlignCenter (aligncenter)
        "\uE1A2", // AlignLeft (alignleft)
        "\uE1A0", // AlignRight (alignright)
        "\uE179", // AllApps (allapps)
        "\uE16C", // Attach (attach)
        "\uE12D", // AttachCamera (attachcamera)
        "\uE189", // Audio (audio)
        "\uE112", // Back (back)
        "\uE1D8", // BackToWindow (backtowindow)
        "\uE1E0", // BlockContact (blockcontact)
        "\uE19B", // Bold (bold)
        "\uE12F", // Bookmarks (bookmarks)
        "\uE155", // BrowsePhotos (browsephotos)
        "\uE133", // Bullets (bullets)
        "\uE1D0", // Calculator (calculator)
        "\uE163", // Calendar (calendar)
        "\uE161", // CalendarDay (calendarday)
        "\uE1DB", // CalendarReply (calendarreply)
        "\uE162", // CalendarWeek (calendarweek)
        "\uE114", // Camera (camera)
        "\uE10A", // Cancel (cancel)
        "\uE15A", // Caption (caption)
        "\uE190", // Cc (cc)
        "\uE1C9", // CellPhone (cellphone)
        "\uE164", // Characters (characters)
        "\uE106", // Clear (clear)
        "\uE1C5", // ClearSelection (clearselection)
        "\uE121", // Clock (clock)
        "\uE126", // ClosePane (closepane)
        "\uE134", // Comment (comment)
        "\uE13D", // Contact (contact)
        "\uE187", // Contact2 (contact2)
        "\uE136", // ContactInfo (contactinfo)
        "\uE181", // ContactPresence (contactpresence)
        "\uE16F", // Copy (copy)
        "\uE123", // Crop (crop)
        "\uE16B", // Cut (cut)
        "\uE107", // Delete (delete)
        "\uE1D1", // Directions (directions)
        "\uE194", // DisableUpdates (disableupdates)
        "\uE17A", // DisconnectDrive (disconnectdrive)
        "\uE19E", // Dislike (dislike)
        "\uE147", // DockBottom (dockbottom)
        "\uE145", // DockLeft (dockleft)
        "\uE146", // DockRight (dockright)
        "\uE130", // Document (document)
        "\uE118", // Download (download)
        "\uE104", // Edit (edit)
        "\uE11D", // Emoji (emoji)
        "\uE170", // Emoji2 (emoji2)
        "\uE113", // Favorite (favorite)
        "\uE16E", // Filter (filter)
        "\uE11A", // Find (find)
        "\uE129", // Flag (flag)
        "\uE188", // Folder (folder)
        "\uE185", // Font (font)
        "\uE186", // FontColor (fontcolor)
        "\uE1C6", // FontDecrease (fontdecrease)
        "\uE1C7", // FontIncrease (fontincrease)
        "\uE1C8", // FontSize (fontsize)
        "\uE111", // Forward (forward)
        "\uE1E9", // FourBars (fourbars)
        "\uE1D9", // FullScreen (fullscreen)
        "\uE12B", // Globe (globe)
        "\uE143", // Go (go)
        "\uE1E4", // GoToStart (gotostart)
        "\uE184", // GoToToday (gototoday)
        "\uE137", // HangUp (hangup)
        "\uE11B", // Help (help)
        "\uE16A", // HideBcc (hidebcc)
        "\uE193", // Highlight (highlight)
        "\uE10F", // Home (home)
        "\uE150", // Import (import)
        "\uE151", // ImportAll (importall)
        "\uE171", // Important (important)
        "\uE199", // Italic (italic)
        "\uE144", // Keyboard (keyboard)
        "\uE11F", // LeaveChat (leavechat)
        "\uE112", // Left (left)
        "\uE1D3", // Library (library)
        "\uE19F", // Like (like)
        "\uE19D", // LikeDislike (likedislike)
        "\uE167", // Link (link)
        "\uE14C", // List (list)
        "\uE119", // Mail (mail)
        "\uE135", // Mail2 (mail2)
        "\uE120", // MailForward (mailforward)
        "\uE172", // MailReply (mailreply)
        "\uE165", // MailReplyAll (mailreplyall)
        "\uE178", // Manage (manage)
        "\uE1C4", // Map (map)
        "\uE17B", // MapDrive (mapdrive)
        "\uE139", // MapPin (mappin)
        "\uE1D5", // Memo (memo)
        "\uE15F", // Message (message)
        "\uE1D6", // Microphone (microphone)
        "\uE10C", // More (more)
        "\uE19C", // MoveToFolder (movetofolder)
        "\uE142", // MusicInfo (musicinfo)
        "\uE198", // Mute (mute)
        "\uE1DA", // NewFolder (newfolder)
        "\uE17C", // NewWindow (newwindow)
        "\uE101", // Next (next)
        "\uE1E6", // OneBar (onebar)
        "\uE1A5", // OpenFile (openfile)
        "\uE197", // OpenLocal (openlocal)
        "\uE127", // OpenPane (openpane)
        "\uE17D", // OpenWith (openwith)
        "\uE14F", // Orientation (orientation)
        "\uE1A6", // OtherUser (otheruser)
        "\uE1CE", // OutlineStar (outlinestar)
        "\uE132", // Page (page)
        "\uE160", // Page2 (page2)
        "\uE16D", // Paste (paste)
        "\uE103", // Pause (pause)
        "\uE125", // People (people)
        "\uE192", // Permissions (permissions)
        "\uE13A", // Phone (phone)
        "\uE1D4", // PhoneBook (phonebook)
        "\uE158", // Pictures (pictures)
        "\uE141", // Pin (pin)
        "\uE18A", // Placeholder (placeholder)
        "\uE102", // Play (play)
        "\uE1D7", // PostUpdate (postupdate)
        "\uE295", // Preview (preview)
        "\uE12A", // PreviewLink (previewlink)
        "\uE100", // Previous (previous)
        "\uE182", // Priority (priority)
        "\uE131", // ProtectedDocument (protecteddocument)
        "\uE166", // Read (read)
        "\uE10D", // Redo (redo)
        "\uE149", // Refresh (refresh)
        "\uE148", // Remote (remote)
        "\uE108", // Remove (remove)
        "\uE13E", // Rename (rename)
        "\uE15E", // Repair (repair)
        "\uE1CD", // RepeatAll (repeatall)
        "\uE1CC", // RepeatOne (repeatone)
        "\uE1DE", // ReportHacked (reporthacked)
        "\uE1CA", // Reshare (reshare)
        "\uE111", // Right (right)
        "\uE14A", // Rotate (rotate)
        "\uE124", // RotateCamera (rotatecamera)
        "\uE105", // Save (save)
        "\uE159", // SaveLocal (savelocal)
        "\uE294", // Scan (scan)
        "\uE14E", // SelectAll (selectall)
        "\uE122", // Send (send)
        "\uE18C", // SetLockScreen (setlockscreen)
        "\uE18D", // SetTile (settile)
        "\uE115", // Settings (settings)
        "\uE14D", // Shop (shop)
        "\uE169", // ShowBcc (showbcc)
        "\uE15C", // ShowResults (showresults)
        "\uE14B", // Shuffle (shuffle)
        "\uE173", // SlideShow (slideshow)
        "\uE1CF", // SolidStar (solidstar)
        "\uE174", // Sort (sort)
        "\uE15B", // Stop (stop)
        "\uE191", // StopSlideShow (stopslideshow)
        "\uE1C3", // Street (street)
        "\uE13C", // Switch (switch)
        "\uE1E1", // SwitchApps (switchapps)
        "\uE117", // Sync (sync)
        "\uE1DF", // SyncFolder (syncfolder)
        "\uE1CB", // Tag (tag)
        "\uE1D2", // Target (target)
        "\uE1E8", // ThreeBars (threebars)
        "\uE1E3", // TouchPointer (touchpointer)
        "\uE12C", // Trim (trim)
        "\uE1E7", // TwoBars (twobars)
        "\uE11E", // TwoPage (twopage)
        "\uE19A", // Underline (underline)
        "\uE10E", // Undo (undo)
        "\uE195", // Unfavorite (unfavorite)
        "\uE196", // Unpin (unpin)
        "\uE1DD", // UnsyncFolder (unsyncfolder)
        "\uE110", // Up (up)
        "\uE11C", // Upload (upload)
        "\uE183", // UploadSkyDrive (uploadskydrive)
        "\uE116", // Video (video)
        "\uE13B", // VideoChat (videochat)
        "\uE18B", // View (view)
        "\uE138", // ViewAll (viewall)
        "\uE15D", // Volume (volume)
        "\uE156", // Webcam (webcam)
        "\uE128", // World (world)
        "\uE1E5", // ZeroBars (zerobars)
        "\uE1A3", // Zoom (zoom)
        "\uE12E", // ZoomIn (zoomin)
        "\uE1A4", // ZoomOut (zoomout)
    ];

    private static readonly Dictionary<string, AppBarIcon> s_byWinJsName = new(StringComparer.OrdinalIgnoreCase)
    {
        ["accept"] = AppBarIcon.Accept,
        ["accounts"] = AppBarIcon.Accounts,
        ["add"] = AppBarIcon.Add,
        ["addfriend"] = AppBarIcon.AddFriend,
        ["admin"] = AppBarIcon.Admin,
        ["aligncenter"] = AppBarIcon.AlignCenter,
        ["alignleft"] = AppBarIcon.AlignLeft,
        ["alignright"] = AppBarIcon.AlignRight,
        ["allapps"] = AppBarIcon.AllApps,
        ["attach"] = AppBarIcon.Attach,
        ["attachcamera"] = AppBarIcon.AttachCamera,
        ["audio"] = AppBarIcon.Audio,
        ["back"] = AppBarIcon.Back,
        ["backtowindow"] = AppBarIcon.BackToWindow,
        ["blockcontact"] = AppBarIcon.BlockContact,
        ["bold"] = AppBarIcon.Bold,
        ["bookmarks"] = AppBarIcon.Bookmarks,
        ["browsephotos"] = AppBarIcon.BrowsePhotos,
        ["bullets"] = AppBarIcon.Bullets,
        ["calculator"] = AppBarIcon.Calculator,
        ["calendar"] = AppBarIcon.Calendar,
        ["calendarday"] = AppBarIcon.CalendarDay,
        ["calendarreply"] = AppBarIcon.CalendarReply,
        ["calendarweek"] = AppBarIcon.CalendarWeek,
        ["camera"] = AppBarIcon.Camera,
        ["cancel"] = AppBarIcon.Cancel,
        ["caption"] = AppBarIcon.Caption,
        ["cc"] = AppBarIcon.Cc,
        ["cellphone"] = AppBarIcon.CellPhone,
        ["characters"] = AppBarIcon.Characters,
        ["clear"] = AppBarIcon.Clear,
        ["clearselection"] = AppBarIcon.ClearSelection,
        ["clock"] = AppBarIcon.Clock,
        ["closepane"] = AppBarIcon.ClosePane,
        ["comment"] = AppBarIcon.Comment,
        ["contact"] = AppBarIcon.Contact,
        ["contact2"] = AppBarIcon.Contact2,
        ["contactinfo"] = AppBarIcon.ContactInfo,
        ["contactpresence"] = AppBarIcon.ContactPresence,
        ["copy"] = AppBarIcon.Copy,
        ["crop"] = AppBarIcon.Crop,
        ["cut"] = AppBarIcon.Cut,
        ["delete"] = AppBarIcon.Delete,
        ["directions"] = AppBarIcon.Directions,
        ["disableupdates"] = AppBarIcon.DisableUpdates,
        ["disconnectdrive"] = AppBarIcon.DisconnectDrive,
        ["dislike"] = AppBarIcon.Dislike,
        ["dockbottom"] = AppBarIcon.DockBottom,
        ["dockleft"] = AppBarIcon.DockLeft,
        ["dockright"] = AppBarIcon.DockRight,
        ["document"] = AppBarIcon.Document,
        ["download"] = AppBarIcon.Download,
        ["edit"] = AppBarIcon.Edit,
        ["emoji"] = AppBarIcon.Emoji,
        ["emoji2"] = AppBarIcon.Emoji2,
        ["favorite"] = AppBarIcon.Favorite,
        ["filter"] = AppBarIcon.Filter,
        ["find"] = AppBarIcon.Find,
        ["flag"] = AppBarIcon.Flag,
        ["folder"] = AppBarIcon.Folder,
        ["font"] = AppBarIcon.Font,
        ["fontcolor"] = AppBarIcon.FontColor,
        ["fontdecrease"] = AppBarIcon.FontDecrease,
        ["fontincrease"] = AppBarIcon.FontIncrease,
        ["fontsize"] = AppBarIcon.FontSize,
        ["forward"] = AppBarIcon.Forward,
        ["fourbars"] = AppBarIcon.FourBars,
        ["fullscreen"] = AppBarIcon.FullScreen,
        ["globe"] = AppBarIcon.Globe,
        ["go"] = AppBarIcon.Go,
        ["gotostart"] = AppBarIcon.GoToStart,
        ["gototoday"] = AppBarIcon.GoToToday,
        ["hangup"] = AppBarIcon.HangUp,
        ["help"] = AppBarIcon.Help,
        ["hidebcc"] = AppBarIcon.HideBcc,
        ["highlight"] = AppBarIcon.Highlight,
        ["home"] = AppBarIcon.Home,
        ["import"] = AppBarIcon.Import,
        ["importall"] = AppBarIcon.ImportAll,
        ["important"] = AppBarIcon.Important,
        ["italic"] = AppBarIcon.Italic,
        ["keyboard"] = AppBarIcon.Keyboard,
        ["leavechat"] = AppBarIcon.LeaveChat,
        ["left"] = AppBarIcon.Left,
        ["library"] = AppBarIcon.Library,
        ["like"] = AppBarIcon.Like,
        ["likedislike"] = AppBarIcon.LikeDislike,
        ["link"] = AppBarIcon.Link,
        ["list"] = AppBarIcon.List,
        ["mail"] = AppBarIcon.Mail,
        ["mail2"] = AppBarIcon.Mail2,
        ["mailforward"] = AppBarIcon.MailForward,
        ["mailreply"] = AppBarIcon.MailReply,
        ["mailreplyall"] = AppBarIcon.MailReplyAll,
        ["manage"] = AppBarIcon.Manage,
        ["map"] = AppBarIcon.Map,
        ["mapdrive"] = AppBarIcon.MapDrive,
        ["mappin"] = AppBarIcon.MapPin,
        ["memo"] = AppBarIcon.Memo,
        ["message"] = AppBarIcon.Message,
        ["microphone"] = AppBarIcon.Microphone,
        ["more"] = AppBarIcon.More,
        ["movetofolder"] = AppBarIcon.MoveToFolder,
        ["musicinfo"] = AppBarIcon.MusicInfo,
        ["mute"] = AppBarIcon.Mute,
        ["newfolder"] = AppBarIcon.NewFolder,
        ["newwindow"] = AppBarIcon.NewWindow,
        ["next"] = AppBarIcon.Next,
        ["onebar"] = AppBarIcon.OneBar,
        ["openfile"] = AppBarIcon.OpenFile,
        ["openlocal"] = AppBarIcon.OpenLocal,
        ["openpane"] = AppBarIcon.OpenPane,
        ["openwith"] = AppBarIcon.OpenWith,
        ["orientation"] = AppBarIcon.Orientation,
        ["otheruser"] = AppBarIcon.OtherUser,
        ["outlinestar"] = AppBarIcon.OutlineStar,
        ["page"] = AppBarIcon.Page,
        ["page2"] = AppBarIcon.Page2,
        ["paste"] = AppBarIcon.Paste,
        ["pause"] = AppBarIcon.Pause,
        ["people"] = AppBarIcon.People,
        ["permissions"] = AppBarIcon.Permissions,
        ["phone"] = AppBarIcon.Phone,
        ["phonebook"] = AppBarIcon.PhoneBook,
        ["pictures"] = AppBarIcon.Pictures,
        ["pin"] = AppBarIcon.Pin,
        ["placeholder"] = AppBarIcon.Placeholder,
        ["play"] = AppBarIcon.Play,
        ["postupdate"] = AppBarIcon.PostUpdate,
        ["preview"] = AppBarIcon.Preview,
        ["previewlink"] = AppBarIcon.PreviewLink,
        ["previous"] = AppBarIcon.Previous,
        ["priority"] = AppBarIcon.Priority,
        ["protecteddocument"] = AppBarIcon.ProtectedDocument,
        ["read"] = AppBarIcon.Read,
        ["redo"] = AppBarIcon.Redo,
        ["refresh"] = AppBarIcon.Refresh,
        ["remote"] = AppBarIcon.Remote,
        ["remove"] = AppBarIcon.Remove,
        ["rename"] = AppBarIcon.Rename,
        ["repair"] = AppBarIcon.Repair,
        ["repeatall"] = AppBarIcon.RepeatAll,
        ["repeatone"] = AppBarIcon.RepeatOne,
        ["reporthacked"] = AppBarIcon.ReportHacked,
        ["reshare"] = AppBarIcon.Reshare,
        ["right"] = AppBarIcon.Right,
        ["rotate"] = AppBarIcon.Rotate,
        ["rotatecamera"] = AppBarIcon.RotateCamera,
        ["save"] = AppBarIcon.Save,
        ["savelocal"] = AppBarIcon.SaveLocal,
        ["scan"] = AppBarIcon.Scan,
        ["selectall"] = AppBarIcon.SelectAll,
        ["send"] = AppBarIcon.Send,
        ["setlockscreen"] = AppBarIcon.SetLockScreen,
        ["settile"] = AppBarIcon.SetTile,
        ["settings"] = AppBarIcon.Settings,
        ["shop"] = AppBarIcon.Shop,
        ["showbcc"] = AppBarIcon.ShowBcc,
        ["showresults"] = AppBarIcon.ShowResults,
        ["shuffle"] = AppBarIcon.Shuffle,
        ["slideshow"] = AppBarIcon.SlideShow,
        ["solidstar"] = AppBarIcon.SolidStar,
        ["sort"] = AppBarIcon.Sort,
        ["stop"] = AppBarIcon.Stop,
        ["stopslideshow"] = AppBarIcon.StopSlideShow,
        ["street"] = AppBarIcon.Street,
        ["switch"] = AppBarIcon.Switch,
        ["switchapps"] = AppBarIcon.SwitchApps,
        ["sync"] = AppBarIcon.Sync,
        ["syncfolder"] = AppBarIcon.SyncFolder,
        ["tag"] = AppBarIcon.Tag,
        ["target"] = AppBarIcon.Target,
        ["threebars"] = AppBarIcon.ThreeBars,
        ["touchpointer"] = AppBarIcon.TouchPointer,
        ["trim"] = AppBarIcon.Trim,
        ["twobars"] = AppBarIcon.TwoBars,
        ["twopage"] = AppBarIcon.TwoPage,
        ["underline"] = AppBarIcon.Underline,
        ["undo"] = AppBarIcon.Undo,
        ["unfavorite"] = AppBarIcon.Unfavorite,
        ["unpin"] = AppBarIcon.Unpin,
        ["unsyncfolder"] = AppBarIcon.UnsyncFolder,
        ["up"] = AppBarIcon.Up,
        ["upload"] = AppBarIcon.Upload,
        ["uploadskydrive"] = AppBarIcon.UploadSkyDrive,
        ["video"] = AppBarIcon.Video,
        ["videochat"] = AppBarIcon.VideoChat,
        ["view"] = AppBarIcon.View,
        ["viewall"] = AppBarIcon.ViewAll,
        ["volume"] = AppBarIcon.Volume,
        ["webcam"] = AppBarIcon.Webcam,
        ["world"] = AppBarIcon.World,
        ["zerobars"] = AppBarIcon.ZeroBars,
        ["zoom"] = AppBarIcon.Zoom,
        ["zoomin"] = AppBarIcon.ZoomIn,
        ["zoomout"] = AppBarIcon.ZoomOut,
    };

    /// <summary>Number of icons in the set.</summary>
    public static int Count => s_glyphs.Length;

    /// <summary>Returns the single-character glyph string for <paramref name="icon"/>.</summary>
    public static string Glyph(AppBarIcon icon)
    {
        var i = (int)icon;
        if ((uint)i >= (uint)s_glyphs.Length)
        {
            throw new ArgumentOutOfRangeException(nameof(icon));
        }

        return s_glyphs[i];
    }

    /// <summary>Returns the codepoint for <paramref name="icon"/>.</summary>
    public static int Codepoint(AppBarIcon icon) => Glyph(icon)[0];

    /// <summary>Resolves a lowercase icon name (<c>"mailreplyall"</c>) or a PascalCase member name to an icon.</summary>
    public static bool TryParse(string? name, out AppBarIcon icon)
    {
        if (!string.IsNullOrEmpty(name) && (s_byWinJsName.TryGetValue(name, out icon) || Enum.TryParse(name, true, out icon)))
        {
            return true;
        }

        icon = default;
        return false;
    }

    /// <summary>All icons in declaration order.</summary>
    public static IReadOnlyList<AppBarIcon> All { get; } = Enum.GetValues<AppBarIcon>();
}
