using System;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.Threading.Tasks;
using Avalonia.Media;
using Avalonia.Media.Imaging;
using Avalonia.Platform;
using AvaWin.Controls;

namespace AvaWin.Gallery.ViewModels;

/// <summary>A bundled placeholder photo (Assets/Photos, generated by tools/gen-images.cs).</summary>
public sealed class Photo
{
    private static readonly Dictionary<int, Bitmap> Cache = new();

    public Photo(int index, string title, string location, DateOnly date)
    {
        Index = index;
        Title = title;
        Location = location;
        Date = date;
    }

    public int Index { get; }

    public string Title { get; }

    public string Location { get; }

    public DateOnly Date { get; }

    public string Caption => $"{Location} · {Date.ToString("MMMM yyyy", System.Globalization.CultureInfo.InvariantCulture)}";

    /// <summary>Decoded once per asset and shared by every page that shows it.</summary>
    public Bitmap Image
    {
        get
        {
            if (!Cache.TryGetValue(Index, out var bitmap))
            {
                using var stream = AssetLoader.Open(new Uri($"avares://AvaWin.Gallery/Assets/Photos/photo-{Index:00}.jpg"));
                Cache[Index] = bitmap = new Bitmap(stream);
            }

            return bitmap;
        }
    }

    public override string ToString() => Title;
}

/// <summary>A contact for the list demos: grouped by the first letter of the name.</summary>
public sealed class Contact
{
    public Contact(string firstName, string lastName, string city, Color color)
    {
        FirstName = firstName;
        LastName = lastName;
        City = city;
        Color = color;
        Brush = new SolidColorBrush(color);
    }

    public string FirstName { get; }

    public string LastName { get; }

    public string Name => FirstName + " " + LastName;

    public string City { get; }

    public string Email => $"{FirstName}.{LastName}@example.com".ToLowerInvariant();

    public string Initials => FirstName[..1] + LastName[..1];

    public string Group => FirstName[..1].ToUpperInvariant();

    public Color Color { get; }

    public IBrush Brush { get; }

    public override string ToString() => Name;
}

/// <summary>A group header item for grouped <see cref="ListView"/> demos and SemanticZoom's zoomed-out view.</summary>
public sealed class ContactGroup
{
    public required string Key { get; init; }

    public required int Count { get; init; }

    public string Title => Key;

    public override string ToString() => Key;
}

public sealed record Album(string Title, string Artist, Photo Cover, IReadOnlyList<Track> Tracks)
{
    public override string ToString() => Title;
}

public sealed record Track(int Number, string Title, string Duration);

public sealed record Article(string Section, string Title, string Summary, Photo Photo)
{
    public override string ToString() => Title;
}

/// <summary>The sample content the pages share: photos, contacts, music and news.</summary>
public static class SampleData
{
    public static readonly Color[] Palette =
    [
        Color.Parse("#4617B4"), Color.Parse("#2672EC"), Color.Parse("#00A600"), Color.Parse("#D24726"),
        Color.Parse("#AA40FF"), Color.Parse("#008299"), Color.Parse("#82BA00"), Color.Parse("#EE1111"),
    ];

    private static readonly string[] FirstNames =
    [
        "Ava", "Ben", "Cara", "Dev", "Eli", "Fay", "Gus", "Hana", "Ivo", "Jun", "Kai", "Lena", "Mo", "Nia", "Omar", "Pia",
        "Quinn", "Rae", "Sam", "Tess", "Uma", "Vik", "Wen", "Xu", "Yara", "Zed", "Aiko", "Bram", "Cleo", "Dara", "Emil",
        "Finn", "Gia", "Hugo", "Ines", "Joel", "Kira", "Leo", "Mira", "Noor", "Otto", "Priya", "Rosa", "Sven", "Tara", "Ulla",
        "Vera", "Will", "Yuki", "Zara", "Ana", "Bo", "Cy", "Dee", "Ed", "Flo", "Gil", "Ida", "Jo", "Kim",
    ];

    private static readonly string[] LastNames =
    [
        "Adler", "Baker", "Chen", "Diaz", "Evans", "Fischer", "Garcia", "Hayes", "Ito", "Jones", "Khan", "Lopez", "Meyer",
        "Novak", "Olsen", "Patel", "Quist", "Rossi", "Silva", "Tanaka", "Ueda", "Vogel", "Weber", "Xie", "Young", "Zimmer",
    ];

    private static readonly string[] Cities =
    [
        "Seattle", "Tokyo", "Berlin", "Lisbon", "Toronto", "Sydney", "Nairobi", "Oslo", "Mumbai", "São Paulo", "Dublin", "Prague",
    ];

    private static readonly (string Title, string Location)[] PhotoInfo =
    [
        ("Harbor at dusk", "Lisbon"), ("Green ridge", "Kyoto"), ("Summit haze", "Chamonix"), ("Terracotta lane", "Marrakesh"),
        ("Violet hour", "Reykjavik"), ("Tide pools", "Big Sur"), ("Spring meadow", "Tuscany"), ("Red canyon", "Sedona"),
        ("Night crossing", "Copenhagen"), ("Lavender fields", "Provence"), ("Neon rain", "Tokyo"), ("Blue morning", "Santorini"),
        ("Golden dunes", "Namib"), ("Fern gully", "Hoh"), ("Clay village", "Cappadocia"), ("Winter pier", "Brighton"),
        ("Purple ridge", "Banff"), ("Harbor lights", "Sydney"), ("Cedar valley", "Yakushima"), ("Ember sky", "Uluru"),
        ("Orchid house", "Singapore"), ("Cold lagoon", "Jökulsárlón"), ("Lime grove", "Sicily"), ("Rust coast", "Cornwall"),
    ];

    /// <summary>All 24 bundled photos.</summary>
    public static IReadOnlyList<Photo> Photos { get; } = PhotoInfo
        .Select((p, i) => new Photo(i + 1, p.Title, p.Location, new DateOnly(2014, 1 + i % 12, 1 + (i * 7) % 28)))
        .ToList();

    /// <summary>The first <paramref name="count"/> contacts, sorted by name.</summary>
    public static List<Contact> Contacts(int count)
    {
        var list = new List<Contact>(count);
        for (var i = 0; i < count; i++)
        {
            list.Add(new Contact(FirstNames[i % FirstNames.Length], LastNames[(i * 7 + i / FirstNames.Length) % LastNames.Length], Cities[(i * 5) % Cities.Length], Palette[i % Palette.Length]));
        }

        return list.OrderBy(c => c.Name, StringComparer.Ordinal).ToList();
    }

    public static List<ContactGroup> Groups(IEnumerable<Contact> contacts) =>
        contacts.GroupBy(c => c.Group).OrderBy(g => g.Key, StringComparer.Ordinal).Select(g => new ContactGroup { Key = g.Key, Count = g.Count() }).ToList();

    public static IReadOnlyList<Album> Albums { get; } =
    [
        new("Northern Lights", "Aurora Field", Photos[4], Tracks("Dawn Chorus", "Glass Fjord", "Halo", "Slow Tide", "Cold Lagoon")),
        new("Terracotta", "The Clay Hands", Photos[3], Tracks("Marrakesh", "Sunset Lane", "Kiln", "Red Dust")),
        new("Green Ridge", "Moss & Stone", Photos[1], Tracks("Cedar", "Fern Gully", "Ridge Walk", "Hollow", "Canopy", "Spring")),
        new("Neon Rain", "City Loop", Photos[10], Tracks("Shibuya", "Wet Asphalt", "Vending Machine", "Last Train")),
        new("Ember Sky", "Red Centre", Photos[19], Tracks("Uluru", "Long Road", "Dust Storm")),
        new("Blue Morning", "Islanders", Photos[11], Tracks("Caldera", "Whitewash", "Ferry", "Windmill", "Salt")),
    ];

    /// <summary>News-style items for the Hub demos; one section per <see cref="Article.Section"/>.</summary>
    public static IReadOnlyList<Article> Articles { get; } =
    [
        new("Top stories", "Harbor district reopens after a year of works", "The waterfront promenade is back with wider walkways, a new tram stop and space for the weekend market.", Photos[0]),
        new("Top stories", "City votes on the green ridge park plan", "A 40-hectare park would connect the two river banks with a cycle bridge.", Photos[1]),
        new("Top stories", "Summit trail closed for the season", "Rangers cite early snow and the lodge's ongoing repairs.", Photos[2]),
        new("Travel", "Terracotta lanes: a walking guide", "Six routes through the old town, from the tanneries to the rooftop cafés.", Photos[3]),
        new("Travel", "Chasing the violet hour", "Where to stand, and when, for the best light on the black-sand coast.", Photos[4]),
        new("Travel", "Tide pools for beginners", "Low-tide walks along the cliffs, with a map of the safest coves.", Photos[5]),
        new("Travel", "Spring in the meadows", "The wildflower season runs late this year; here is where it's peaking.", Photos[6]),
        new("Science", "Red canyon rocks tell a 200-million-year story", "New dating puts the layers older than expected.", Photos[7]),
        new("Science", "Night crossing: mapping the bridge's vibrations", "Sensors will run through winter to model wind loads.", Photos[8]),
        new("Science", "The lavender genome", "Researchers sequence the fragrant crop to breed drought tolerance.", Photos[9]),
        new("Culture", "Neon rain: the photo show", "Fifty images of the city after dark, on until March.", Photos[10]),
        new("Culture", "Blue morning at the island theater", "A new open-air stage opens with a week of dawn concerts.", Photos[11]),
        new("Culture", "Golden dunes on film", "The desert epic returns to cinemas in a restored print.", Photos[12]),
        new("Culture", "Fern gully sound walk", "An audio tour through the old-growth forest, narrated by its rangers.", Photos[13]),
    ];

    /// <summary>An <see cref="ISupportIncrementalLoading"/> source that fabricates contact pages on demand.</summary>
    public sealed class IncrementalContacts : ObservableCollection<Contact>, ISupportIncrementalLoading
    {
        private readonly int _max;

        public IncrementalContacts(int initial, int max)
        {
            _max = max;
            foreach (var c in Enumerable.Range(0, initial).Select(Make))
            {
                Add(c);
            }
        }

        public int LoadCalls { get; private set; }

        public bool HasMoreItems => Count < _max;

        public async Task<int> LoadMoreItemsAsync(int count)
        {
            LoadCalls++;
            await Task.Delay(400);
            var start = Count;
            for (var i = 0; i < count && Count < _max; i++)
            {
                Add(Make(start + i));
            }

            return Count - start;
        }

        private static Contact Make(int i) => new(FirstNames[i % FirstNames.Length], LastNames[(i * 3) % LastNames.Length], Cities[i % Cities.Length], Palette[i % Palette.Length]);
    }

    private static IReadOnlyList<Track> Tracks(params string[] titles) =>
        titles.Select((t, i) => new Track(i + 1, t, $"{3 + (i * 7) % 3}:{(10 + i * 13) % 60:00}")).ToList();
}
